### ISSUE TITLE
Any plans to support Symfony 6.*

### ISSUE THREAD

**Issue by roed** [prokki/htpasswd#2]
Really love your bundle! Do you have any plans to support symfony 6? Your bundle still uses the deprecated User and that will prevent us from upgrading to symfony 6.

**Comment by prokki** [comment]
Hi @roed I am sorry for the delay.

It should be easy to update the reqpositpry but I am currently full of work and private stuff. You can send a pull request or you have to wait a little bit.

**Comment by prokki** [comment]
Updated bundle to Symfony v6

https://github.com/prokki/htpasswd/releases/tag/1.0

Upgrade instructions:
- The new requirements are in tag *1.\**: Please udpate your composer dependency to
  ```
   "prokki/htpasswd": "^1.0"
  ```
- The project's namesspace has changed: Please rename your `use` statements in your files
  from ~`use Htpasswd\....`~ to `use Prokki\Htpasswd\....`

Please keep in mind that all changes are not tested because there are no unit tests and I personally do not have any project running on Symfony v6. Feel free to contribute, add tests and/or post bugs :smile:
